/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package virussimulation;

import javax.swing.JOptionPane;

/**
 *
 * @author Jorrit
 */
public class JFrame extends javax.swing.JFrame {
    public int populatieB, contactenB;
    public boolean gezondB, vaccB;
    public double alfaB, betaB;
    public boolean loopEnd = false;
    /**
     * Creates new form JFrame
     */
    public JFrame() {
        initComponents();
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Populatie = new javax.swing.JLabel();
        bPopulatie = new javax.swing.JTextField();
        Alfa = new javax.swing.JLabel();
        bAlfa = new javax.swing.JTextField();
        Beta = new javax.swing.JLabel();
        bBeta = new javax.swing.JTextField();
        Contacten = new javax.swing.JLabel();
        bContacten = new javax.swing.JTextField();
        bGezondheid = new javax.swing.JCheckBox();
        bVaccinatie = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Virus Simulator");

        Populatie.setText("Populatie:");

        bPopulatie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPopulatieActionPerformed(evt);
            }
        });

        Alfa.setText("Alfa:");

        bAlfa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAlfaActionPerformed(evt);
            }
        });

        Beta.setText("Beta:");

        bBeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBetaActionPerformed(evt);
            }
        });

        Contacten.setText("Contacten:");

        bContacten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bContactenActionPerformed(evt);
            }
        });

        bGezondheid.setText("Gezondheid");
        bGezondheid.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                bGezondheidAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                bGezondheidAncestorRemoved(evt);
            }
        });

        bVaccinatie.setText("Vaccinatie");
        bVaccinatie.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                bVaccinatieAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                bVaccinatieAncestorRemoved(evt);
            }
        });

        jButton1.setText("Run");
        jButton1.setToolTipText("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Contacten)
                    .addComponent(Beta)
                    .addComponent(Alfa)
                    .addComponent(Populatie))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bPopulatie, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bAlfa, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bBeta, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bContacten, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bGezondheid)
                            .addComponent(bVaccinatie))))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(Populatie)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bPopulatie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bGezondheid))
                .addGap(9, 9, 9)
                .addComponent(Alfa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bAlfa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bVaccinatie))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Beta, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bBeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(Contacten)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bContacten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void bPopulatieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPopulatieActionPerformed
        try {
            populatieB = Integer.parseInt(this.bPopulatie.getText());
        }
        catch (NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Not a number", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bPopulatieActionPerformed

    private void bGezondheidAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_bGezondheidAncestorAdded
           gezondB = true;
    }//GEN-LAST:event_bGezondheidAncestorAdded

    private void bAlfaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAlfaActionPerformed
        try {
            double alfaB = Double.parseDouble(this.bAlfa.getText());
        }
        catch (NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Not a number", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bAlfaActionPerformed

    private void bGezondheidAncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_bGezondheidAncestorRemoved
        gezondB = false;
    }//GEN-LAST:event_bGezondheidAncestorRemoved

    private void bVaccinatieAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_bVaccinatieAncestorAdded
        vaccB = true;
    }//GEN-LAST:event_bVaccinatieAncestorAdded

    private void bVaccinatieAncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_bVaccinatieAncestorRemoved
        vaccB = false;
    }//GEN-LAST:event_bVaccinatieAncestorRemoved

    private void bBetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBetaActionPerformed
        try {
            betaB = Double.parseDouble(this.bBeta.getText());
        }
        catch (NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Not a number", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bBetaActionPerformed

    private void bContactenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bContactenActionPerformed
        try {
            contactenB = Integer.parseInt(this.bContacten.getText());
        }
        catch (NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Not a number", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bContactenActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        loopEnd = false;
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Alfa;
    private javax.swing.JLabel Beta;
    private javax.swing.JLabel Contacten;
    private javax.swing.JLabel Populatie;
    public javax.swing.JTextField bAlfa;
    public javax.swing.JTextField bBeta;
    private javax.swing.JTextField bContacten;
    private javax.swing.JCheckBox bGezondheid;
    public javax.swing.JTextField bPopulatie;
    private javax.swing.JCheckBox bVaccinatie;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
